### ISSUE TITLE
When not Hovering Over an Item, Item Value Macro Sends "c" Key

### ISSUE THREAD

**Issue by dsnvwlmnt** [thirdy/POE-TradeMacro#36] opened 2016-10-15 11:40 UTC
I have the C keyboard key assigned to the Events & PvP tab. If i'm not hovering over an item when i click my shortcut key for the item trade value search*, it opens/closes the Events & PvP tab.

* (according to trade_config.ini, default is ctrl+x, but i changed it to F3 in there)

**Comment by Eruyome** [comment] 2016-10-15 12:12
To run any search we need the items data, therefore every search function (ctrl+x) also triggers ctrl+c. No way around that. Using ctrl+c closes the event tab (when assigned to c) even without using any macro, So I suggest using c for the default "open character screen" (no problems here) or don't use the macro.

**Closed** 2016-10-15 12:14 UTC

**Comment by dsnvwlmnt** [comment] 2016-10-15 14:17
This issue is not resolved, don't know why you closed it. Whether my C key is assigned to the character sheet or rebound to something else should be irrelevant. Have you hardcoded something that assumes people don't rebind their C key?

Also, are you really suggesting that a solution to the problem, is to not use POE-TradeMacro? I truly hope i'm misunderstanding you here. That reasoning could be used to close every issue that ever came up. Issue? Don't use the program. :P

**Comment by Eruyome** [comment] 2016-10-15 15:53
I told you the problem is not related to the Macro. It happens even without the Macro when you press ctrl+c. And pressing ctrl+c is THE ONLY WAY to get the items data from PoE into the clipboard.

**Comment by dsnvwlmnt** [comment] 2016-10-15 21:20
I see, i didn't catch that subtlety. Surprised to hear it's a bug with PoE. I'll post a bug report to their forums. Thanks.
